# Generated by Django 5.1 on 2024-09-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSearch',
        ),
    ]
