# Generated by Django 5.1 on 2024-09-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
